#!/usr/bin/env python
# File: funcs.py
# Author: Junfeng Li <li424@mcmaster.ca>
# Description: generate function finger

import matplotlib.pyplot as plt
import inspect

blacklists = [
    'show',
    'savefig',
    'fill',
    'isinteractive',
    'close',
    'connect',
    'get',
    'hist',
    'step',
    'xcorr',
    ]

funcs = inspect.getmembers(plt, inspect.isfunction)

## function fingers
with open("funcs.jl", "w") as f:
    f.write("#!/usr/bin/env julia\n"
            "# File: funcs.jl\n"
            "# Author: Junfeng Li <li424@mcmaster.ca>\n"
            "# Description: function name of matplotlib.pyplot.\n"
            "# Do not edit manully. It is generated by funcs.py\n")
    f.write('\n')
    f.write("funcs = (\n")
    for func in funcs:
        func = func[0]  # get function name
        if func[0] != '_' and not func in blacklists:
            f.write(':')
            f.write(func)
            f.write(',\n')
    f.write(")")
